name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
      - master
    types:
      # milestone changes
      - milestoned
      - demilestoned
      # label changes for â€œno milestoneâ€
      - labeled
      - unlabeled
      # initial check
      - opened
      - edited
      - reopened
      # code change (e.g. this workflow)
      - synchronize

jobs:
  # This job verifies that the milestone is present or not necessary.
  check-milestone:
    name: Check Milestone
    runs-on: ubuntu-latest
    steps:
      - name: Check if milestone or â€œno milestoneâ€ label is present
        uses: flying-sheep/check@v1
        with:
          success: ${{ github.event.pull_request.milestone != null || contains(github.event.pull_request.labels.*.name, 'no milestone') }}
  # This job verifies if the required checkboxs are checked and determines if â€œcheck-relnotesâ€ needs to be run.
  checklist:
    name: Checklist
    runs-on: ubuntu-latest
    steps:
      - name: Check if the â€œCloses issueâ€ checkbox is checked
        uses: kaisugi/action-regex-match@v1.0.0
        id: checked-issue
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '^\s*- \[x\] Closes'
          flags: m
      - name: Check if the â€œTestsâ€ checkbox is checked
        uses: kaisugi/action-regex-match@v1.0.0
        id: checked-tests
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '^\s*- \[x\] Tests'
          flags: m
      - name: Check if the â€œRelease notesâ€ checkbox is checked and filled
        uses: kaisugi/action-regex-match@v1.0.0
        id: checked-relnotes
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '^\s*- \[x\] Release notes not necessary because:(.*)$'
          flags: m
      - name: Verify that the closes issue and tests checkboxes are checked
        uses: flying-sheep/check@v1
        with:
          success: ${{ steps.checked-issue.outputs.match != '' && steps.checked-tests.outputs.match != '' }}
    outputs:
      no-relnotes-reason: ${{ steps.checked-relnotes.outputs.group1 }}
  # This job verifies that the relevant release notes file has been modified.
  check-relnotes:
    name: Check for release notes
    runs-on: ubuntu-latest
    needs: checklist
    if: ${{ needs.checklist.outputs.no-relnotes-reason == '' && !contains(github.event.pull_request.labels.*.name, 'Development Process ğŸš€') }}
    steps:
      - uses: actions/checkout@v3
      - name: Find out if relevant release notes are modified
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: | # this is intentionally a string
            relnotes: 'docs/release-notes/${{ github.event.pull_request.milestone.title }}.md'
      - name: Check if relevant release notes are modified
        uses: flying-sheep/check@v1
        with:
          success: ${{ steps.changes.outputs.relnotes }}
